# SITE CONFIGURATION
baseurl: ""
url: "https://camp5803.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Jiyong's Study
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "Blog of a student who wants to become a Web Developer" # used by search engines

  # Header and footer text
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type Theme</a>

  # Icons
  rss: false
  email_address: "camp803@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "profile.php?id=100008302009757"
  flickr:
  gitlab:
  github: "camp5803"
  gitter:
  google_plus:
  instagram: "const_jiyong"
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
exclude:
  - Gemfile
    - Gemfile.lock

# .
remote_theme: rohanchandra/type-theme

